service: MoonMail-v2-campaigns

plugins:
  - serverless-plugin-optimize

provider:
  name: aws
  runtime: nodejs6.10
  profile: ${self:custom.config.PROFILE}
  region: ${self:custom.config.REGION}
  timeout: 300
  environment:
    REGION: ${self:custom.config.REGION}
    EVENTS_ROUTER_STREAM_NAME:
      Fn::ImportValue: EventsRouterStreamName-${self:custom.currentStage}

package:
  individually: true

custom:
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}
  resourcesPrefix: ${self:service}-${self:custom.currentStage}
  config: ${file(./config.${self:custom.currentStage}.json)}

functions:
  processSesNotification:
    handler: handler.hello

