service: MoonMail-v2-emails

plugins:
  - serverless-plugin-optimize

provider:
  name: aws
  runtime: nodejs6.10
  profile: ${self:custom.config.PROFILE}
  region: ${self:custom.config.REGION}
  timeout: 300
  environment:
    REGION: ${self:custom.config.REGION}
    EVENTS_ROUTER_STREAM_NAME: ${self:custom.config.EVENTS_ROUTER_STREAM_NAME}

package:
  individually: true

custom:
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}
  resourcesPrefix: ${self:service}-${self:custom.currentStage}
  config: ${file(./config.${self:custom.currentStage}.json)}

functions:
  processSesNotification:
    handler: handler.processSesNotification
    events:
      - sns:
          arn:
            Ref: EmailNotificationsTopic

resources:
  Resources:
    EmailNotificationsTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: ${self:custom.resourcesPrefix}-EmailNotificationsTopic
    EmailNotificationsTopicPolicy:
      Type: "AWS::SNS::TopicPolicy"
      Properties:
        PolicyDocument:
          Statement:
            -
              Effect: Allow
              Principal:
                AWS: "*"
              Action: "SNS:Publish"
              Resource:
                Ref: EmailNotificationsTopic
        Topics:
          -
            Ref: EmailNotificationsTopic
